### ISSUE TITLE
unable to push

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/bibliography#10]
I can't push my updates:

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.

error: failed to push some refs to 'git@github.com:dragonfly-science/bibliography.git'

**Comment by katrin-berkenbusch** [comment]
the content of the pre-push file is:

#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"

**Comment by finlay** [comment]
It doesn't seem to be necessary. I am not at all sure where this came from.

Delete the the hook, and try pushing again.

**Comment by katrin-berkenbusch** [comment]
sounds good. thanks.

**Comment by katrin-berkenbusch** [comment]
Yes, that worked. thanks again.
