### ISSUE TITLE
Keeping apa-note.csl and apa-nobib.csl in sync?

### ISSUE THREAD

**Issue by spl** [dragonfly-science/bibliography#2]
As of the creation of `apa-note.csl`, the files `apa-note.csl` and `apa-nobib.csl` are no longer duplicates modulo the existence of the `<bibliography>` section. Do you want to keep them identical in other ways, or does that not matter?

As an aside, I read about dependent styles in CSL with the hope that we could have a dependent `.csl` with only the bibliography and a reference to the independent `.csl`. But that idea is apparently not included in the spec. I didn't actually try to see if it would work that way, however.

**Comment by edwardabraham** [comment]
We are using the `apa-note.csl` and `apa-nobib.csl` styles on the Dragonfly website, but we aren't tracking changes to the upstream `apa.csl`. I am going to move these files to the Dragonfly Website and close this issue here.
